export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_MYSKY_USER_PUBLIC_KEY = 'SET_MYSKY_USER_PUBLIC_KEY';
export const SET_MYSKY_USER_PROPOSALS_LIKED = 'SET_MYSKY_USER_PROPOSALS_LIKED';
export const SET_PROPOSAL_RECORDS = 'SET_PROPOSAL_RECORDS';
export const SET_PROPOSAL_COMMENTS_SKYLINK = 'SET_PROPOSAL_COMMENTS_SKYLINK';
export const SET_MYSKY_INSTANCE = 'SET_MYSKY_INSTANCE';


export const SET_IS_MODAL_DETAILS_POPUP_OPEN = 'SET_IS_MODAL_DETAILS_POPUP_OPEN';